### ISSUE TITLE
rmats.result <- read.table("./SE.MATS.JC.txt", sep = "\t", header = T) issue

### ISSUE THREAD

**Issue by AlbertRockG** [huqiwen0313/HM_splicing#3]
Hey, 

I'm performing an analysis with HMsplicing package on rmats v4.1.0  output, but it yields this error : 

> setwd("~/Desktop/rmats/rnaseq-mats_output")
> library(HMSplicing)
Warning messages:
1: replacing previous import ‘ggplot2::margin’ by ‘iRF::margin’ when loading ‘HMSplicing’ 
2: replacing previous import ‘dplyr::combine’ by ‘iRF::combine’ when loading ‘HMSplicing’ 
> rmats.result <- read.table("./SE.MATS.JC.txt", sep = "\t", header = T)
> rmatsClassified <- classify_splicing_code(rmats.result)
Error in `$<-.data.frame`(`*tmp*`, "class", value = 0) : 
  replacement has 1 row, data has 0

As a newbie in R, I don't really know how to solve it. So please help me.

**Comment by huqiwen0313** [comment]
Hi @AlbertRockG ,

Would you please provide an example of your input data (SE.MATS.JC.txt) so that I can take a look at it ?

**Comment by AlbertRockG** [comment]
Thanks for your answer. Kindly find in the attached file the input data. 
[SE.MATS.JC.txt](https://github.com/huqiwen0313/HM_splicing/files/6350578/SE.MATS.JC.txt)

**Comment by huqiwen0313** [comment]
I think this issue comes from there is no differences of the inclusion level for the exons you are looking at. You can see the pvalues in you rmats file are all 1, which means that the exon regions you are trying to look at are mostly likely not alternative spliced. 

summary(rmats.result$PValue)
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
      1       1       1       1       1       1 

It should work if you use the regions that have alternative splicing events.

**Comment by AlbertRockG** [comment]
Thank you for your help. I finally notice it.
